## Switches
# SW0 -> sw_adr[0]
set_property PACKAGE_PIN V17 [get_ports {sw_adr[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_adr[0]}]
# SW1 -> sw_adr[1]
set_property PACKAGE_PIN V16 [get_ports {sw_adr[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_adr[1]}]
# SW2 -> sw_adr[2]
set_property PACKAGE_PIN W16 [get_ports {sw_adr[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_adr[2]}]
# SW3 -> sw_adr[3]
set_property PACKAGE_PIN W17 [get_ports {sw_adr[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_adr[3]}]
# SW4 -> sw_adr[4]
set_property PACKAGE_PIN W15 [get_ports {sw_adr[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_adr[4]}]

# SW15 -> sw_bank (Sayfa Seçici)
set_property PACKAGE_PIN R2 [get_ports {sw_bank}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_bank}]

## LEDs (LD0 - LD15)
set_property PACKAGE_PIN U16 [get_ports {led[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]

## Voltaj ve Yapılandırma Kısıtları
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]